apiVersion: apps/v1
kind: Deployment
metadata: 
  generation: 1
  labels:
    app: manual-pv-task
  name: manual-pv-task
  namespace: test 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: manual-pv-task 
  template:
    metadata: 
      labels:
        app: manual-pv-task
    spec:      
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent 
        name: manual-pv-busybox  
        command:
        - "sh"
        - "-c"
        args:
        - while true; do 
            echo "busybox $(date '+%d.%m.%y %H:%M')">/mnt/data/currenttime; 
            sleep 5; 
          done
        volumeMounts:
        - mountPath: "/mnt/data"
          name: manual-pv-storage
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent 
        name: manual-pv-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http
        - containerPort: 11443
          name: https
        volumeMounts:
        - mountPath: "/mnt/data"
          name: manual-pv-storage
      
      volumes:
        - name: manual-pv-storage
          persistentVolumeClaim:
            claimName: manual-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always  
      terminationGracePeriodSeconds: 30