apiVersion: apps/v1
kind: Deployment
metadata: 
  generation: 1
  labels:
    app: nfs-pv-task
  name: nfs-pv-task
  namespace: test 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-pv-task 
  template:
    metadata: 
      labels:
        app: nfs-pv-task
    spec:      
      containers: 
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent 
        name:  multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http
        - containerPort: 11443
          name: https
        volumeMounts:
        - mountPath: "/mnt/data"
          name:  storage
      
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: nfc-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always  
      terminationGracePeriodSeconds: 30